name: Generate woff fonts from ttf fonts

on:
  # runs every hour
  schedule:
    - cron: '0 * * * *'
  # allow manually trigger
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Magic 😎
        run: |
          # Get the latest version
          LATEST_VERSION=$(curl -fsSL https://api.github.com/repos/jonz94/Sarasa-Gothic-Nerd-Fonts/releases/latest | jq -r .tag_name | cut -d v -f 2)
          echo Latest version of jonz94/Sarasa-Gothic-Nerd-Fonts is ${LATEST_VERSION}

          # Get the current version
          CURRENT_VERSION=$(cat ${GITHUB_WORKSPACE}/ci/VERSION)
          echo Current version is ${CURRENT_VERSION}

          if [[ "$LATEST_VERSION" == "$CURRENT_VERSION" ]]; then
            echo Two versions are the same
            echo Everything is up to date!
            exit 0
          fi

          echo Two versions are different
          echo Starting generate new fonts

          # cleanup outputs directory
          rm -fr ${GITHUB_WORKSPACE}/ci/outputs

          echo Downloading Sarasa Gothic Nerd Fonts ${LATEST_VERSION}
          curl -L https://github.com/jonz94/Sarasa-Gothic-Nerd-Fonts/releases/download/v${LATEST_VERSION}/sarasa-mono-tc-nerd-font.zip --create-dirs -o ${GITHUB_WORKSPACE}/ci/outputs/sarasa-mono-tc-nerd-font.zip

          unzip ${GITHUB_WORKSPACE}/ci/outputs/sarasa-mono-tc-nerd-font.zip -d ${GITHUB_WORKSPACE}/ci/outputs

          # generate woff fonts using fonttools
          pip install fonttools
          python ${GITHUB_WORKSPACE}/ci/scripts/main.py

          echo ${LATEST_VERSION} > ${GITHUB_WORKSPACE}/ci/VERSION

          git config user.name github-actions
          git config user.email github-actions@github.com
          git add -A
          git commit -m "🤖 ci: update fonts to v${LATEST_VERSION}"
          git push
